create table archived_reservations (id integer not null auto_increment, classroom varchar(255) not null, name varchar(255), note varchar(255) not null, semester varchar(255), subject varchar(255), username varchar(255) not null, primary key (id))
create table authorities (id integer not null auto_increment, name varchar(255) not null, primary key (id))
create table buildings (id integer not null auto_increment, name varchar(255) not null, primary key (id))
create table classrooms (id integer not null auto_increment, chairs integer not null, has_pc bit not null, has_projector bit not null, name varchar(255) not null, building integer not null, primary key (id))
create table reservation_dates (id integer not null auto_increment, end tinyblob not null, start tinyblob not null, reservation integer not null, primary key (id))
create table reservations (reservation_type varchar(31) not null, id integer not null auto_increment, note varchar(255) not null, name varchar(255), classroom integer not null, statuses integer not null, users integer not null, semester integer, subject integer, primary key (id))
create table semesters (id integer not null auto_increment, end_date date not null, name varchar(11) not null, start_date date not null, primary key (id))
create table statuses (id integer not null auto_increment, message varchar(255) not null, name varchar(255) not null, primary key (id))
create table subjects (id integer not null auto_increment, code varchar(255) not null, name varchar(255) not null, primary key (id))
create table users (id integer not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id))
create table users_authorities (authority_id integer not null, user_id integer not null)
alter table authorities add constraint UK_nb3atvjf9ov5d0egnuk47o5e unique (name)
alter table buildings add constraint UK_lf8jhhsls7j5q6n95vlbnlhe7 unique (name)
alter table semesters add constraint UK_ci1s5s8npb7j044md3s0wdhsh unique (name)
alter table statuses add constraint UK_9ob63rkqg8ppaon1l37w8id2p unique (name)
alter table subjects add constraint UK_rg7x1lyii7kdyycw98d45vep5 unique (code)
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username)
alter table classrooms add constraint FKlj1lfjtnb25trjy7u16qnul6v foreign key (building) references buildings (id)
alter table reservation_dates add constraint FKoywxoho7q2a6v1beuvquvuk4e foreign key (reservation) references reservations (id)
alter table reservations add constraint FKt95ee9ji25fmarld5y3ec6kk9 foreign key (classroom) references classrooms (id)
alter table reservations add constraint FKp6jc0qpjwce44n67guvhcon7r foreign key (statuses) references statuses (id)
alter table reservations add constraint FKanj0k1ypjumq29tgajndr41hm foreign key (users) references users (id)
alter table reservations add constraint FK4ne95xvhbxbpscjppu5ou8vt2 foreign key (semester) references semesters (id)
alter table reservations add constraint FKa71du7jlpfq5yf9gyg3b99amw foreign key (subject) references subjects (id)
alter table users_authorities add constraint FKq3lq694rr66e6kpo2h84ad92q foreign key (user_id) references users (id)
alter table users_authorities add constraint FKdsfxx5g8x8mnxne1fe0yxhjhq foreign key (authority_id) references authorities (id)
