--Elso inditas eseten futtatando!

/*
DELETE FROM STATUSES;
DELETE FROM AUTHORITIES;
DELETE FROM TYPES;
*/
/*
INSERT INTO STATUSES VALUES (1, 'A foglalas feldolgozas alatt!', 'PENDING');
INSERT INTO STATUSES VALUES (2, 'A foglalas feldolgozva!', 'ACCEPTED');
INSERT INTO STATUSES VALUES (3, 'A foglalas elutasitva!', 'DECLINED');

INSERT INTO AUTHORITIES VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITIES VALUES (2, 'ROLE_ADMIN');

INSERT INTO TYPES VALUES (1, 'EVENT');
INSERT INTO TYPES VALUES (2, 'SIMPLE');
INSERT INTO TYPES VALUES (3, 'SEMESTER');
*/
